# Generated by Django 5.0.1 on 2025-05-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_importjob_match_column_mapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='mpn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='ean',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='lead_time',
            field=models.CharField(default='3 days', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='match_method',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='payment_terms',
            field=models.CharField(default='Net 30', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.product'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('supplier', 'product'), name='unique_supplier_product'),
        ),
    ]
