# Generated by Django 5.0.1 on 2025-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supplierproduct_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_instock_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='asin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bought_past_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_box_seller_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='dominant_seller_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_monthly_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='fba_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='fba_sellers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='live_offers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='referral_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='upc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
