# Generated by Django 5.0.1 on 2025-05-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_amazon_instock_rate_product_asin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='error_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='processed_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='total_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.TextField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('In Progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('processing', 'Processing')]),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='type',
            field=models.TextField(choices=[('Amazon Data', 'Amazon Data'), ('Supplier Data', 'Supplier Data'), ('product', 'Product'), ('supplier', 'Supplier')]),
        ),
    ]
