# Generated by Django 5.0.1 on 2025-05-17 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_importhistory_completed_at_importhistory_error_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Custom Formula', max_length=255)),
                ('formula_items', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profit_formulas',
                'indexes': [models.Index(fields=['user'], name='profit_form_user_id_23bc12_idx'), models.Index(fields=['is_default'], name='profit_form_is_defa_ca7afa_idx')],
            },
        ),
    ]
